language: ruby
rvm:
  - 1.9.2
before_install:
  - export TZ=Europe/London
before_script:
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - export CUCUMBER_FORMAT=progress
sudo: false
cache: bundler
