language: ruby
dist: xenial
sudo: required
services:
  - mysql
  - xvfb
cache: bundler
before_install:
  - export TZ=Europe/London
before_script:
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - export CUCUMBER_FORMAT=progress
script:
  - bundle exec rubocop
  - bundle exec rake
