language: ruby
bundler_args: "--without deployment"
dist: xenial
sudo: required
services:
- mysql
- xvfb
cache: bundler
before_install:
- export TZ=Europe/London
before_script:
- bundle exec rake db:create db:schema:load RAILS_ENV=test
- bundle exec rake db:test:prepare
- export CUCUMBER_FORMAT=progress
script:
- bundle exec rubocop
- xvfb-run -a bundle exec rake
before_deploy: "./compile-build"
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/asset_audits
  api_key:
    secure: X+FF6+9rbdF15fk6AHNru7r4lcvv0rumGXkijGWJTbbAXvfWyMzM1La041nEfLvGfZdVMGrOXpK2hAVXlFD+gLocdSkRH1zonldqfU5YWoLUUy8IksgDqwXkEuZt1SGsAe10hDIrGX6WirctBO9e5TTvDwBJndQ/A0b1UsOkI9g=

