language: ruby
bundler_args: "--without deployment"
dist: xenial
sudo: required
services:
- mysql
- xvfb
cache: bundler
before_install:
- export TZ=Europe/London
before_script:
- bundle exec rake db:create db:schema:load RAILS_ENV=test
- bundle exec rake db:test:prepare
- export CUCUMBER_FORMAT=progress
script:
- bundle exec rubocop
- xvfb-run -a bundle exec rake
before_deploy: "./compile-build"
deploy:
  provider: releases
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: radome/asset_audits
  api_key:
    secure: UetDOeKexCYnlnSSTgp2miPAwTm40tHI2k/NZP0sytjfzspxNzG1Dp86esRSQ8c0DV2baV27u6E/CcKVsBavLYZqG8dxWfMou0VUscn57MH9QDyxJseS3uNuj6p4lt6zLPQrrPY3m8hsWRpRloVSx40DdpcNkTEnWqKHOqy76yzM230asHYqeTyGqazTWPfDvB/2BLooAfTi35ED80yYgQDFrbqe7oACYnFDGyT33Riy/qdkk1vf3TAdgyWxRnjkt43jvP+B7lNnY/Hhk5vlvo2HjzOfQ67AGFXbRlqM61X3xgCKnv+ZsvfZdIVJN2KScR9FYrH/f57TlTm9Tzp6Kz5Z7rsVE9+zWfN1Fi6i4ozI7m3P86pq2dfgykYEke3DTnDMp0ay9Mi2Ul8oPwtNI4iR06eronmLWefzoRXaNOEjy4KEeWe86fTmV1rCxMlpQ/RG4Z9JwSBhHpwOqGHesMh0AFtAFD45LyxNELoykwTKwpERccu706ZnmPTysZKB/nI0JgrdJoFO7UyTUahgo9EWS3lVwHeN4uopms0Aw2SPE3ipQh8fMx1jrUJQGmXMgq/BjxIiZ78JD7WwmOyuqxpCjjlKVIuuzrvLumca41aSiHDakxansOKpEnWMDRz8PScD2grFqzOPZfU4Rs+PNJm9tFIuwQHoA20t2QUBy6g=

