sequencescape_api_v2: http://sequencescape/api/v2
sequencescape_api_v1: http://localhost:3000/api/1/
sequencescape_authorisation: cucumber
search_find_assets_by_barcode: 00000000-0000-0000-0000-000000000001
